# Generated by Django 5.2.8 on 2025-11-23 20:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code promo')),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe'), ('free_delivery', 'Livraison gratuite')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Pourcentage (0-100) ou montant fixe', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Montant minimum de commande', max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Montant maximum de réduction (pour les pourcentages)', max_digits=10, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('usage_limit', models.IntegerField(blank=True, help_text="Nombre total d'utilisations autorisées", null=True)),
                ('usage_limit_per_user', models.IntegerField(default=1, help_text="Nombre d'utilisations par utilisateur")),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='exclusive_coupons', to=settings.AUTH_USER_MODEL)),
                ('applicable_restaurants', models.ManyToManyField(blank=True, related_name='coupons', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promotions.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='commandes.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisation de coupon',
                'verbose_name_plural': 'Utilisations de coupons',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la promotion')),
                ('description', models.TextField(blank=True)),
                ('promotion_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe'), ('buy_x_get_y', 'Achetez X obtenez Y')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Pourcentage ou montant fixe de réduction', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('buy_quantity', models.IntegerField(blank=True, help_text='Quantité à acheter', null=True)),
                ('get_quantity', models.IntegerField(blank=True, help_text='Quantité gratuite', null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('applicable_days', models.JSONField(blank=True, default=list, help_text='Jours de la semaine où la promotion est active')),
                ('start_time', models.TimeField(blank=True, help_text='Heure de début (ex: happy hour)', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Heure de fin', null=True)),
                ('priority', models.IntegerField(default=0, help_text='Plus élevé = plus prioritaire')),
                ('image', models.ImageField(blank=True, upload_to='promotions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_items', models.ManyToManyField(blank=True, related_name='promotions', to='restaurants.menuitem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
