# Generated by Django 5.2.8 on 2025-11-23 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('message', models.TextField(max_length=200, verbose_name='Message')),
                ('target_all_customers', models.BooleanField(default=False, verbose_name='Tous les clients')),
                ('target_favorites', models.BooleanField(default=False, verbose_name='Clients ayant mis en favori')),
                ('target_previous_orders', models.BooleanField(default=False, verbose_name='Clients ayant déjà commandé')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Planifiée'), ('sent', 'Envoyée'), ('cancelled', 'Annulée')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('menu', 'Ouvrir le menu'), ('promotion', 'Voir la promotion'), ('order', 'Commander')], default='menu', max_length=20)),
                ('action_data', models.JSONField(blank=True, default=dict, help_text="Données pour l'action (ex: promotion_id)")),
                ('recipients_count', models.IntegerField(default=0, verbose_name='Destinataires')),
                ('delivered_count', models.IntegerField(default=0, verbose_name='Délivrées')),
                ('opened_count', models.IntegerField(default=0, verbose_name='Ouvertes')),
                ('clicked_count', models.IntegerField(default=0, verbose_name='Cliquées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_campaigns', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Campagne push',
                'verbose_name_plural': 'Campagnes push',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('banner', "Bannière dans l'app"), ('featured', 'Restaurant mis en avant'), ('promotion', 'Promotion spéciale'), ('sponsored', 'Résultat sponsorisé')], max_length=20)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, upload_to='advertisements/')),
                ('target_cities', models.JSONField(blank=True, default=list, help_text='Villes ciblées (si vide, toutes)')),
                ('target_age_min', models.IntegerField(blank=True, null=True)),
                ('target_age_max', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Active'), ('paused', 'En pause'), ('completed', 'Terminée')], default='draft', max_length=20)),
                ('budget', models.DecimalField(decimal_places=2, help_text='Budget total de la campagne (€)', max_digits=10)),
                ('cost_per_click', models.DecimalField(decimal_places=2, default=0.5, help_text='Coût par clic (€)', max_digits=6)),
                ('impressions', models.IntegerField(default=0, verbose_name='Impressions')),
                ('clicks', models.IntegerField(default=0, verbose_name='Clics')),
                ('conversions', models.IntegerField(default=0, verbose_name='Conversions (commandes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Publicité',
                'verbose_name_plural': 'Publicités',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('in_app', "Dans l'application")], max_length=20)),
                ('title_template', models.CharField(help_text='Variables: {restaurant_name}, {item_name}, {price}, {discount}', max_length=200)),
                ('message_template', models.TextField(help_text='Variables: {restaurant_name}, {item_name}, {price}, {discount}, {address}')),
                ('default_image', models.ImageField(blank=True, upload_to='share_templates/')),
                ('hashtags', models.JSONField(blank=True, default=list, help_text='Liste de hashtags à ajouter')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_templates', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Template de partage',
                'verbose_name_plural': 'Templates de partage',
                'ordering': ['platform', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('in_app', "Dans l'application")], max_length=20)),
                ('share_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('menu_item', 'Article du menu'), ('promotion', 'Promotion')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('share_url', models.URLField(blank=True, verbose_name='Lien de partage')),
                ('views', models.IntegerField(default=0, verbose_name='Vues')),
                ('clicks', models.IntegerField(default=0, verbose_name='Clics')),
                ('shares_count', models.IntegerField(default=0, verbose_name='Partages')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='restaurants.menuitem')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='promotions.promotion')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_shares', to='restaurants.restaurant')),
                ('shared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partage social',
                'verbose_name_plural': 'Partages sociaux',
                'ordering': ['-shared_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_new_items', models.BooleanField(default=True, verbose_name='Nouveaux articles')),
                ('notify_promotions', models.BooleanField(default=True, verbose_name='Promotions')),
                ('notify_events', models.BooleanField(default=False, verbose_name='Événements')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_subscriptions', to='restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement newsletter',
                'verbose_name_plural': 'Abonnements newsletter',
                'ordering': ['-subscribed_at'],
                'unique_together': {('restaurant', 'user')},
            },
        ),
    ]
